In [1]:
import numpy as np
np.arange(1,51)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [2]:
np.arange(2,101,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [3]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [4]:
marks = np.array([

78, 85, 92, 67, 88,

73, 95, 60, 84, 91

])

total=np.sum(marks)
print(total)
Average=np.mean(marks)
print(Average)
Max=np.max(marks)
print(Max)
Min=np.min(marks)
print(Min)
Median=np.median(marks)
print(Median)

813
81.3
95
60
84.5


In [5]:
marks = np.array([

78, 85, 92, 67, 88,

73, 95, 60, 84, 91

])

Above_90=marks[marks>90]
print(Above_90)
above_average=marks[marks>(np.mean(marks))]
print(above_average)
Below_70=marks[marks<70]
print(Below_70)


[92 95 91]
[85 92 88 95 84 91]
[67 60]


In [6]:
numbers=np.arange(1,21,1)
numbers.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [7]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

row=matrix[1,:]
print(row)
column=matrix[:,1]
print(column)
single_Element=matrix[1,2]
print(single_Element)


[40 50 60]
[20 50 80]
60


In [8]:
a = np.array([10, 20, 30, 40, 50])

b = np.array([5, 10, 15, 20, 25])
addition=a+b
print(addition)
substraction=a-b
print(substraction)
mul=a*b
print(mul)
div=a/b
print(div)

[15 30 45 60 75]
[ 5 10 15 20 25]
[  50  200  450  800 1250]
[2. 2. 2. 2. 2.]


In [9]:
random_num=np.random.randint(1,1000,100)
mean=random_num.mean()
print(mean)
median=np.median(random_num)
print(median)
std=np.std(random_num).round(2)
print(std)
variance=np.var(random_num).round(2)
print(variance)

505.96
592.0
298.98
89387.12


In [10]:
unsorted=np.random.randint(1,100,15)
ascending=np.sort(unsorted)
print(ascending)
descending=np.sort(unsorted)[::-1]
print(descending)


[ 8 18 21 22 31 39 40 50 63 73 81 81 81 86 88]
[88 86 81 81 81 73 63 50 40 39 31 22 21 18  8]


In [11]:
unique_val=np.array([1,2,2,3,3,3,4,5,5,6])
print(np.unique(unique_val))

[1 2 3 4 5 6]


In [12]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

d = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])
add=c+d
print(add)
sub=c-d
print(sub)
element=c*d
print(element)
matrix=c@d
print(matrix)

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [13]:

salary = np.array([
    30000,
    35000,
    40000,
    45000,
    50000,
    55000,
    60000,
    65000,
    70000,
    75000,
    80000,
    85000,
    90000,
    95000,
    100000
])

highest=np.max(salary)
print(highest)
lowest=np.min(salary)
print(lowest)
Average=np.mean(salary)
print(Average)
above_avg=salary[salary>salary.mean()]
print(above_avg)


100000
30000
65000.0
[ 70000  75000  80000  85000  90000  95000 100000]


In [14]:
random_matrix=np.random.randint(1,100,(5,5))
print(random_matrix)

Maximum_value=np.max(random_matrix)
print(Maximum_value)
Minimum_value=np.min(random_matrix)
print(Minimum_value)
Row_sum=np.sum(random_matrix , axis=1)
print(Row_sum)
Col_sum=np.sum(random_matrix , axis=0)
print(Col_sum)
avg=np.mean(random_matrix)
print(avg)

[[ 6 36 40 79 77]
 [96  6 45 84 69]
 [53 14 51 43 32]
 [35 99  4 72  6]
 [53 19  3 36 26]]
99
3
[238 300 193 216 137]
[243 174 143 314 210]
43.36
